name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Steve-Fenton/pnpm-updater@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update_script: 'pnpm run refresh'
